TestAssignmentDionysus/Models/Auction.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssignmentDionysus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
    }
}

TestAssignmentDionysus/Models/Bid.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssignmentDionysus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int Id { get; set; }
        public Nullable<int> AuctionId { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<double> Sum { get; set; }
    
        public virtual Auction Auction { get; set; }
    }
}

TestAssignmentDionysus/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAssignmentDionysus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestAssignment20190408111127_dbEntities : DbContext
    {
        public TestAssignment20190408111127_dbEntities()
            : base("name=TestAssignment20190408111127_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
    }
}

TestAssignmentDionysus/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Martin\source\repos\TestAssignmentDionysus\TestAssignmentDionysus\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

TestAssignmentDionysus/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

TestAssignmentDionysus/Controllers/AuctionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using TestAssignmentDionysus.Models;

namespace TestAssignmentDionysus.Controllers
{
    public class AuctionsController : Controller
    {
        public static string endtimeString(DateTime dt)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("en-US");
            string result = dt.ToString();
            Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture("et-EE");
            return result;
        }

        private TestAssignment20190408111127_dbEntities db = new TestAssignment20190408111127_dbEntities();

        public static Auction getById(int id)
        {
            TestAssignment20190408111127_dbEntities db = new TestAssignment20190408111127_dbEntities();
            Auction auction = db.Auctions.Find(id);
            return auction;
        }

        // GET: Auctions
        public ActionResult Index()
        {
            foreach (var auction in db.Auctions)
            {
                var timeLeft = auction.EndTime - DateTime.Now;
                if (timeLeft <= new TimeSpan(0, 0, 0))
                {
                    auction.Status = 2;
                }
            }
            db.SaveChanges();
            return View(db.Auctions.ToList());
        }

        // GET: Auctions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Auction auction = db.Auctions.Find(id);
            if (auction == null)
            {
                return HttpNotFound();
            }
            return View(auction);
        }
    }
}

TestAssignmentDionysus/Controllers/BidsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TestAssignmentDionysus.Models;

namespace TestAssignmentDionysus.Controllers
{
    public class BidsController : Controller
    {
        private TestAssignment20190408111127_dbEntities db = new TestAssignment20190408111127_dbEntities();

        // GET: Bids/Create
        public ActionResult Create()
        {
            string urlParameter = RouteData.Values["id"] + Request.Url.Query;
            int aucId = int.Parse(urlParameter.Split('=')[1]);
            ViewBag.AucId = aucId;

            ViewBag.AuctionId = new SelectList(db.Auctions, "Id", "ProductName");
            return View();
        }

        // POST: Bids/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AuctionId,User,Time,Sum")] Bid bid)
        {
            bid.Time = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.Bids.Add(bid);
                db.SaveChanges();
                return RedirectToAction("Index", "Auctions");
            }

            ViewBag.AuctionId = new SelectList(db.Auctions, "Id", "ProductName", bid.AuctionId);
            return View(bid);
        }      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestAssignmentDionysus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestAssignmentDionysus.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Auctions");
        }
    }
}

TestAssignmentDionysus/Views/Auctions/Index.cshtml
@model IEnumerable<TestAssignmentDionysus.Models.Auction>

@{
    ViewBag.Title = "Index";
}

<h2>Käimasolevad oksjonid</h2>

@foreach (var item in Model.Where(x => x.Status == 1))
{
    if (item.Status == 1)
    {
        <div style="width:300px;height:350px;display:inline-block;background-color:lemonchiffon;padding:30px;margin:20px;border-radius:20px;border:3px solid #ffcc00">
            <p class="text">Toote nimi: @item.ProductName</p>
            <img src="https://cdn.shopify.com/s/files/1/0198/0812/products/MysteryBox_large.jpg?v=1480433527" style="height:100px;width:100px;" />
            <p class="text">Kirjeldus: @item.ProductDescription</p>
            <p>Aega jäänud:</p>
            <div id="@item.Id"></div>
            <script>
                var CountDown = function (data) {
                    // Assign this object
                    var thisObj = this;
                    // Make sure all settings are not left undefined
                    data.send_to = (typeof data.send_to === "undefined") ? "time1" : data.send_to;
                    data.backcolor = (typeof data.backcolor === "undefined") ? "lemonchiffon" : data.backcolor;
                    data.forecolor = (typeof data.forecolor === "undefined") ? "black" : data.forecolor;
                    data.targetdate = (typeof data.targetdate === "undefined") ? "12/31/2020 5:00 AM" : data.targetdate;
                    data.displayformat = (typeof data.displayformat === "undefined") ? "%%D%% Päeva, %%H%% Tundi, %%M%% Minutit, %%S%% Sekundit." : data.displayformat;
                    data.countactive = (typeof data.countactive === "undefined") ? true : data.countactive;
                    data.message = (typeof data.message === "undefined") ? "Ended" : data.message;
                    data.countstepper = (typeof data.countstepper != "number") ? -1 : data.countstepper;
                    data.leadingzero = (typeof data.leadingzero === "undefined") ? true : data.leadingzero;
                    // Get DOM object
                    var domObj = document.getElementById(data.send_to);

                    this.calcage = function (secs, num1, num2) {
                        var s = ((Math.floor(secs / num1)) % num2).toString();

                        if (data.leadingzero && s.length < 2)
                            s = "0" + s;

                        return "<b>" + s + "</b>";
                    }

                    this.putSpan = function (backcolor, forecolor) {
                        // Modify html instead of making html
                        domObj.style.backgroundColor = backcolor;
                        domObj.style.color = forecolor;
                    }

                    this.writeBoard = function (secs, countDownEngine) {
                        if (secs <= 0) {
                            clearInterval(countDownEngine);
                            domObj.innerHTML = data.message;
                            location.reload();
                            return;
                        }

                        var DisplayStr = '';
                        DisplayStr = data.displayformat.replace(/%%D%%/g, thisObj.calcage(secs, 86400, 100000));
                        DisplayStr = DisplayStr.replace(/%%H%%/g, thisObj.calcage(secs, 3600, 24));
                        DisplayStr = DisplayStr.replace(/%%M%%/g, thisObj.calcage(secs, 60, 60));
                        DisplayStr = DisplayStr.replace(/%%S%%/g, thisObj.calcage(secs, 1, 60));
                        domObj.innerHTML = DisplayStr;
                    }

                    this.create = function () {
                        data.countstepper = Math.ceil(data.countstepper);

                        if (data.countstepper == 0)
                            data.countactive = false;

                        var SetTimeOutPeriod = ((Math.abs(data.countstepper) - 1) * 1000) + 990;

                        thisObj.putSpan(data.backcolor, data.forecolor);

                        var dthen = new Date(data.targetdate);
                        var dnow = new Date();
                        var nowCalc = (data.countstepper > 0) ? (dnow - dthen) : (dthen - dnow);
                        var ddiff = new Date(nowCalc);
                        var gsecs = Math.floor((ddiff.valueOf() / 1000));

                        var countDownEngine = setInterval(function () {
                            gsecs = gsecs + data.countstepper;
                            thisObj.writeBoard(gsecs, countDownEngine);
                        }, 1000);
                    }
                }
                // Create instance of your countdown with it's own settings
                var counter = new CountDown({
                    // This is the id name for the container (<div id="time1"></div>)
                    send_to: '@item.Id',
                    forecolor: 'red',
                    targetdate: '@TestAssignmentDionysus.Controllers.AuctionsController.endtimeString(item.EndTime ?? DateTime.Now)'
                });

                // Apply the creation method
                // Without .create(), nothing will happen since all the working
                // script to apply the counter is in this method
                counter.create();

            </script>
            @Html.ActionLink("Tee pakkumine", "Create", "Bids", new { AuctionId = item.Id }, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
}

TestAssignmentDionysus/Views/Bids/Create.cshtml
@model TestAssignmentDionysus.Models.Bid

@{
    ViewBag.Title = "Create";
}

<h2>Uus pakkumine</h2>

<dl class="dl-horizontal">
    <dt>
        Toote nimi:
    </dt>

    <dd>
        @TestAssignmentDionysus.Controllers.AuctionsController.getById(ViewBag.AucId).ProductName
    </dd>

    <dt>
        Toote kirjeldus:
    </dt>

    <dd>
        @TestAssignmentDionysus.Controllers.AuctionsController.getById(ViewBag.AucId).ProductDescription
    </dd>

    <dt>
        Lõpptähtaeg:
    </dt>

    <dd>
        @TestAssignmentDionysus.Controllers.AuctionsController.getById(ViewBag.AucId).EndTime
    </dd>

</dl>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <strong class="control-label col-md-2">Sisesta oma täisnimi</strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.User, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.User, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <strong class="control-label col-md-2">Sisesta summa eurodes</strong>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Esita" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tagasi", "Index", "Auctions")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TestAssignmentDionysus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

TestAssignmentDionysus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dionysus</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <img src="https://image.flaticon.com/icons/svg/1277/1277711.svg" style="height:45px; width:45px" />
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dionysus", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Oksjonikeskus Dionysus</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>